# Generated by Django 4.2.4 on 2024-04-02 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_time',
            field=models.TimeField(default=datetime.datetime(2024, 4, 2, 20, 43, 46, 681518, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 2, 20, 44, 45, 274419, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Check', 'Check'), ('Mpesa', 'Mpesa'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateField(auto_now=True, default=datetime.datetime(2024, 4, 2, 20, 44, 49, 223366, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
