# Generated by Django 4.2.4 on 2024-05-15 11:45

from django.db import migrations, models
import django.db.models.deletion
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('id', utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('unit_number', models.CharField(max_length=255)),
                ('size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('monthly_rent', models.IntegerField(null=True)),
                ('unit_type', models.CharField(blank=True, choices=[('Apartment', 'Apartment'), ('Studio', 'Studio'), ('Single Room', 'Single Room'), ('Shop', 'Shop'), ('Office', 'Office'), ('Warehouse', 'Warehouse'), ('Garage', 'Garage'), ('Restaurant', 'Restaurant'), ('Clinic', 'Clinic')], max_length=50, null=True)),
                ('account', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Vacant', 'Vacant'), ('Occupied', 'Occupied')], default='Vacant', max_length=50)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('tenant', models.CharField(max_length=50)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('vacated_date', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.units')),
            ],
            options={
                'db_table': 'unit_assignment',
            },
        ),
    ]
