# Generated by Django 4.2.4 on 2024-11-10 09:25

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_alter_assignment_id_alter_units_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='status',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Rented', 'Rented')], default='Vacant', max_length=50),
        ),
    ]
