# Generated by Django 4.2.4 on 2023-09-18 09:24

from django.db import migrations, models
import django.utils.timezone
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('id', utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.JSONField(blank=True, null=True)),
                ('latlng', models.JSONField(blank=True, null=True)),
                ('bounds', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('owner', models.JSONField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=100)),
                ('images', models.ManyToManyField(blank=True, related_name='property_images', to='files.files')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
            },
        ),
    ]
