# Generated by Django 4.2.4 on 2024-10-30 15:13

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.CharField(default=4695631407398734815, max_length=255),
            preserve_default=False,
        ),
    ]
