# Generated by Django 4.2.4 on 2024-11-09 08:59

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_unit_count_alter_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_units',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
