# Generated by Django 4.2.4 on 2024-04-02 20:44

import datetime
from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_files_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 2, 20, 43, 50, 986218, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='updated_at',
            field=models.DateField(auto_now=True, default=datetime.datetime(2024, 4, 2, 20, 43, 59, 972236, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
