# Generated by Django 4.2.4 on 2024-04-03 07:44

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_files_created_at_alter_files_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
