# Generated by Django 4.2.4 on 2023-10-14 07:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        ('properties', '0001_initial'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('id', utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('tenant', models.CharField(max_length=100, null=True)),
                ('term', models.CharField(blank=True, choices=[('Fixed Term', 'Fixed Term'), ('Month-To-Month', 'Month-To-Month')], max_length=50, null=True)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('first_rent_date', models.DateField(blank=True, null=True)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('rent_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Every 2 Weeks', 'Every 2 Weeks'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi Annual', 'Semi Annual'), ('Annually', 'Annually')], max_length=50)),
                ('due_day', models.IntegerField(null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('account', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.files')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.units')),
            ],
            options={
                'verbose_name_plural': 'Leases',
                'db_table': 'leases',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('tenant', models.CharField(max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_on', models.DateField()),
                ('amount_paid', models.IntegerField(blank=True, default=0, null=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Check', 'Check'), ('Cash', 'Cash'), ('Mpesa', 'Mpesa'), ('Bank', 'Bank')], max_length=255, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Fully Paid', 'Fully Paid'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Overdue', 'Overdue')], default='Unpaid', max_length=100)),
                ('account', models.CharField(max_length=50)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='leases.lease')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.units')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('item', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceBills', to='leases.invoice')),
            ],
            options={
                'verbose_name_plural': 'Bills',
                'db_table': 'bills',
            },
        ),
    ]
