# Generated by Django 4.2.4 on 2024-04-02 20:44

import datetime
from django.db import migrations, models
import django.utils.timezone
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_alter_lease_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 2, 20, 44, 11, 123382, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bills',
            name='updated_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lease',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='updated_at',
            field=models.DateField(auto_now=True, default=datetime.datetime(2024, 4, 2, 20, 44, 40, 733620, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
