# Generated by Django 4.2.4 on 2024-02-07 16:47

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0007_alter_bills_amount_alter_lease_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='security_deposit',
            field=models.IntegerField(null=True),
        ),
    ]
