# Generated by Django 4.2.4 on 2024-02-07 20:48

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0008_alter_bills_amount_alter_invoice_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
