# Generated by Django 4.2.4 on 2024-12-04 08:17

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0009_alter_lease_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='term',
            field=models.CharField(blank=True, choices=[('Fixed Term', 'Fixed Term'), ('Month-To-Month', 'Month-To-Month'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Quarterly', 'Quarterly'), ('Semi Annual', 'Semi Annual'), ('Annually', 'Annually'), ('Rent-to-Own', 'Rent-to-Own'), ('Commercial', 'Commercial')], max_length=50, null=True),
        ),
    ]
