# Generated by Django 4.2.4 on 2024-02-08 18:12

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0009_alter_bills_amount_alter_lease_id_alter_lease_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='security_deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
