# Generated by Django 4.2.4 on 2024-02-10 16:40

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0010_alter_lease_id_alter_lease_security_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Fully Paid', 'Fully Paid'), ('Outstanding', 'Outstanding'), ('Partially Paid', 'Partially Paid'), ('Due', 'DUE'), ('Overdue', 'Overdue')], default='Outstanding', max_length=100),
        ),
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled'), ('Balance Due', 'Balance Due')], default='Active'),
        ),
    ]
