# Generated by Django 4.2.4 on 2024-03-24 13:37

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0013_lineitem_alter_lease_id_alter_bills_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='account',
            field=models.CharField(default=8793298932, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=utils.utils.CustomUUIDField(default=utils.utils.CustomUUIDField.generate_uuid, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
